services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      TZ: ${TZ}    # optional: set desired timezone
      NTFY_AUTH_FILE: '/var/lib/ntfy/user.db'
      NTFY_AUTH_DEFAULT_ACCESS: 'deny-all'
    # user: UID:GID # optional: replace with your own user/group or uid/gid
    volumes:
      - ${VOLUME_DIR}/ntfy:/var/cache/ntfy
      - ${CONFIG_DIR}/ntfy:/etc/ntfy
    # ports:
    #   - 80:80
    networks:
      - traefik
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    init: true # needed, if healthcheck is used. Prevents zombie processes
    labels:
      - autoheal=true
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.ntfy-rtr.entrypoints=websecure
      - traefik.http.routers.ntfy-rtr.rule=Host(`ntfy.$FQDN`)
      - traefik.http.routers.ntfy-rtr.tls=true
      ## Middlewares
      - traefik.http.routers.ntfy-rtr.middlewares=chain-no-auth@file # No Authentication
      # - traefik.http.routers.ntfy-rtr.middlewares=chain-basic-auth@file # Basic Authentication
      # - traefik.http.routers.ntfy-rtr.middlewares=chain-oauth2-proxy@file # OAuth 2.0
      ## HTTP Services
      - traefik.http.routers.ntfy-rtr.service=ntfy-svc
      - traefik.http.services.ntfy-svc.loadbalancer.server.port=80

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik
